// LoudnessBatch™
// Copyright © 2026 Sheldon Davidson.
// Licensed under the MIT License. See LICENSE.
// SPDX-License-Identifier: MIT

import {analyzePcm,integratedLufs,median,percentile} from './audio-core.js';
const $=s=>document.querySelector(s); const els={files:$('#files'),cancel:$('#cancel'),status:$('#status'),progressText:$('#progressText'),progress:$('#progress'),warnings:$('#warnings'),overview:$('#overview'),rows:$('#rows'),modeHelp:$('#modeHelp'),insightTitle:$('#insightTitle'),insight:$('#insight'),loudnessChart:$('#loudnessChart'),crestChart:$('#crestChart'),corrChart:$('#corrChart'),exportCsv:$('#exportCsv'),exportJson:$('#exportJson')};
let results=[],cancelled=false,mode='reference',audioCtx=null;
function fmt(v,d=1){return Number.isFinite(v)?v.toFixed(d):'—'}
function esc(s=''){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
async function getAudioContext(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();return audioCtx}
async function resample(buffer){if(buffer.sampleRate===48000){return Array.from({length:Math.min(2,buffer.numberOfChannels)},(_,i)=>Float32Array.from(buffer.getChannelData(i)))}const channels=Math.min(2,buffer.numberOfChannels),length=Math.ceil(buffer.duration*48000),OAC=window.OfflineAudioContext||window.webkitOfflineAudioContext;const offline=new OAC(channels,length,48000);const src=offline.createBufferSource();src.buffer=buffer;src.connect(offline.destination);src.start();const rendered=await offline.startRendering();return Array.from({length:channels},(_,i)=>Float32Array.from(rendered.getChannelData(i)))}
function sectionMetrics(channels){const n=channels[0]?.length||0;if(n<19200)return [];const third=Math.floor(n/3),labels=['Start','Middle','End'];return labels.map((label,i)=>{const start=i*third,end=i===2?n:(i+1)*third;const segment=channels.map(c=>c.slice(start,end));return {label,lufs:integratedLufs(segment,48000)}})}
async function analyzeFile(file){const ctx=await getAudioContext();const raw=await file.arrayBuffer();const decoded=await ctx.decodeAudioData(raw.slice(0));const channels=await resample(decoded);const metrics=analyzePcm(channels,48000);return {name:file.name,size:file.size,duration:decoded.duration,sampleRate:decoded.sampleRate,channels:decoded.numberOfChannels,...metrics,sections:sectionMetrics(channels)}}
async function scan(files){cancelled=false;results=[];els.cancel.disabled=false;els.warnings.textContent='';const list=[...files];els.status.textContent=`Analyzing ${list.length} file${list.length===1?'':'s'}…`;const failed=[];for(let i=0;i<list.length;i++){if(cancelled)break;try{results.push(await analyzeFile(list[i]))}catch(e){failed.push(`${list[i].name}: ${e.message}`)}els.progress.style.width=`${(i+1)/list.length*100}%`;els.progressText.textContent=`${i+1} / ${list.length}`;render()}els.cancel.disabled=true;els.status.textContent=cancelled?`Cancelled with ${results.length} completed.`:`Analysis complete — ${results.length} track${results.length===1?'':'s'}.`;if(failed.length)els.warnings.textContent=`${failed.length} file(s) could not be decoded in this browser.`;render()}
function stat(label,value){return `<div class="stat"><strong>${value}</strong><span>${label}</span></div>`}
function renderOverview(){const lufs=results.map(r=>r.lufs).filter(Number.isFinite),peak=results.map(r=>r.samplePeakDb).filter(Number.isFinite),dur=results.reduce((a,r)=>a+r.duration,0);els.overview.innerHTML=[stat('Tracks',results.length),stat('Median LUFS',lufs.length?fmt(median(lufs)):'—'),stat('Loudness span',lufs.length>1?`${fmt(Math.min(...lufs))}…${fmt(Math.max(...lufs))}`:'—'),stat('Highest sample peak',peak.length?`${fmt(Math.max(...peak))} dBFS`:'—'),stat('Total duration',`${Math.floor(dur/60)}m ${Math.round(dur%60)}s`),stat('Clipped samples',results.reduce((a,r)=>a+r.clipSamples,0).toLocaleString())].join('')}
function renderRows(){els.rows.innerHTML=results.map((r,i)=>`<tr><td>${i===0&&mode==='reference'?'<b>MY MIX</b> · ':''}${esc(r.name)}</td><td>${fmt(r.lufs)}</td><td>${fmt(r.samplePeakDb)} dBFS</td><td>${fmt(r.estimatedTruePeakDb)} dB</td><td>${fmt(r.rmsDb)} dBFS</td><td>${fmt(r.crestDb)} dB</td><td>${fmt(r.correlation,2)}</td><td>${r.clipSamples.toLocaleString()}</td></tr>`).join('')}
function card(label,value,text=''){return `<div class="insight-card"><strong>${value}</strong><span>${label}${text?` · ${text}`:''}</span></div>`}
function referenceInsight(){els.insightTitle.textContent='Reference comparison';els.modeHelp.textContent='First analyzed track is treated as your mix; the rest form the reference set.';if(results.length<2){els.insight.innerHTML='<p>Add your mix first, then one or more reference tracks.</p>';return}const mix=results[0],refs=results.slice(1),refL=refs.map(r=>r.lufs).filter(Number.isFinite),refC=refs.map(r=>r.crestDb),refCorr=refs.map(r=>r.correlation);const med=median(refL);els.insight.innerHTML=card('Mix vs reference median',`${fmt(mix.lufs-med)} LU`,`${fmt(mix.lufs)} vs ${fmt(med)} LUFS`)+card('Crest factor difference',`${fmt(mix.crestDb-median(refC))} dB`)+card('Stereo correlation difference',fmt(mix.correlation-median(refCorr),2))+(refL.length>2?card('Reference 10–90% range',`${fmt(percentile(refL,.1))}…${fmt(percentile(refL,.9))} LUFS`):'')}
function albumInsight(){els.insightTitle.textContent='Album / EP consistency';els.modeHelp.textContent='Compares every track to the batch median and surfaces measurable outliers.';if(!results.length){els.insight.innerHTML='<p>Add an album or EP to analyze consistency.</p>';return}const med=median(results.map(r=>r.lufs)),medC=median(results.map(r=>r.crestDb));const ordered=[...results].sort((a,b)=>Math.abs(b.lufs-med)-Math.abs(a.lufs-med));els.insight.innerHTML=card('Album median',`${fmt(med)} LUFS`)+card('Median crest factor',`${fmt(medC)} dB`)+ordered.slice(0,4).map(r=>card(esc(r.name),`${r.lufs>=med?'+':''}${fmt(r.lufs-med)} LU`,'from album median')).join('')}
function crateInsight(){els.insightTitle.textContent='DJ crate consistency';els.modeHelp.textContent='Shows whole-track loudness changes between adjacent files in the selected order.';if(results.length<2){els.insight.innerHTML='<p>Add at least two tracks in approximate set/crate order.</p>';return}let html='';for(let i=1;i<results.length;i++){const d=results[i].lufs-results[i-1].lufs;html+=card(`${esc(results[i-1].name)} → ${esc(results[i].name)}`,`${d>=0?'+':''}${fmt(d)} LU`,Math.abs(d)>=2.5?'large whole-track change':'')}els.insight.innerHTML=html}
function revisionInsight(){els.insightTitle.textContent='Revision difference';els.modeHelp.textContent='Compares the first two files by global measurements. It does not claim sample-aligned null-test results.';if(results.length<2){els.insight.innerHTML='<p>Add two revisions of the same mix.</p>';return}const a=results[0],b=results[1];els.insight.innerHTML=card('Integrated loudness',`${fmt(b.lufs-a.lufs)} LU`)+card('Sample peak',`${fmt(b.samplePeakDb-a.samplePeakDb)} dB`)+card('RMS',`${fmt(b.rmsDb-a.rmsDb)} dB`)+card('Crest factor',`${fmt(b.crestDb-a.crestDb)} dB`)+card('Stereo correlation',fmt(b.correlation-a.correlation,2))}
function sectionInsight(){els.insightTitle.textContent='Section analysis';els.modeHelp.textContent='Splits each track into start, middle and end thirds so quiet intros do not completely hide section-level changes.';if(!results.length){els.insight.innerHTML='<p>Add tracks to compare broad sections.</p>';return}els.insight.innerHTML=results.slice(0,8).map(r=>`<div class="insight-card"><strong>${esc(r.name)}</strong><span>${r.sections.map(s=>`${s.label} ${fmt(s.lufs)} LUFS`).join(' · ')}</span></div>`).join('')}
function renderInsight(){({reference:referenceInsight,album:albumInsight,crate:crateInsight,revision:revisionInsight,sections:sectionInsight}[mode]||referenceInsight)()}
function renderBars(root,values,getValue,format){const pairs=values.map(x=>[x.name,getValue(x)]).filter(x=>Number.isFinite(x[1]));if(!pairs.length){root.innerHTML='<p>No data yet.</p>';return}const min=Math.min(...pairs.map(x=>x[1])),max=Math.max(...pairs.map(x=>x[1]));root.innerHTML=pairs.slice(0,14).map(([name,v])=>{const pct=max===min?100:8+(v-min)/(max-min)*92;return `<div class="barrow"><span class="barlabel" title="${esc(name)}">${esc(name)}</span><div class="bartrack"><div class="barfill" style="width:${pct}%"></div></div><span class="barvalue">${format(v)}</span></div>`}).join('')}
function renderCharts(){renderBars(els.loudnessChart,results,r=>r.lufs,v=>`${fmt(v)} LUFS`);renderBars(els.crestChart,results,r=>r.crestDb,v=>`${fmt(v)} dB`);renderBars(els.corrChart,results,r=>r.correlation,v=>fmt(v,2))}
function render(){renderOverview();renderRows();renderInsight();renderCharts()}
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function download(name,type,text){const b=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCsv(){const keys=['name','duration','sampleRate','channels','lufs','samplePeakDb','estimatedTruePeakDb','rmsDb','crestDb','correlation','clipSamples','dcOffset'];download('loudnessbatch.csv','text/csv',[keys.join(','),...results.map(r=>keys.map(k=>csvEscape(r[k])).join(','))].join('\n'))}
function exportJson(){download('loudnessbatch.json','application/json',JSON.stringify({schema:1,created:new Date().toISOString(),mode,tracks:results},null,2))}
els.files.onchange=e=>scan(e.target.files);els.cancel.onclick=()=>cancelled=true;document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;render()});els.exportCsv.onclick=exportCsv;els.exportJson.onclick=exportJson;render();
